name: Data Pipeline Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL & Data Quality Pipeline
        # This is the key change: we set a working directory for the command
        working-directory: ./scripts
        run: python etl_pipeline.py

      - name: Upload Data Warehouse Artifact
        # This step runs only if the previous steps succeed
        uses: actions/upload-artifact@v3
        with:
          name: olist-data-warehouse
          path: output/olist_master.parquet