name: Data Pipeline Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL & Data Quality Pipeline
        # This command is now run from the project root
        run: python scripts/etl_pipeline.py

      - name: Upload Data Warehouse Artifact
        # This step runs only if the previous steps succeed
        uses: actions/upload-artifact@v3
        with:
          name: olist-data-warehouse
          path: output/olist_master.parquet